import assert from 'node:assert/strict';
import { normalizeCart, addProduct, changeQuantity, unitCents } from './src/cartState.js';
import products from './src/data.js';
let cart = addProduct([], products[0]).cart;
assert.ok(addProduct(cart, products[0]).warning);
assert.ok(addProduct(cart, products[1]).warning);
cart = addProduct(cart, products[4]).cart;
cart = addProduct(cart, products[4]).cart;
assert.equal(cart[1].quantity, 2);
assert.equal(cart.reduce((sum, row) => sum + unitCents(products.find(p => p.id === row.id)) * row.quantity, 0), 5697);
cart = changeQuantity(cart, 5, 3);
assert.equal(cart[1].quantity, 3);
for (const value of [0, -1, 1.5, NaN, Infinity, 2001]) assert.deepEqual(changeQuantity(cart, 5, value), cart);
assert.deepEqual(changeQuantity(cart, 1, 2), cart);
assert.deepEqual(normalizeCart(JSON.parse(JSON.stringify(cart))), cart);
assert.deepEqual(normalizeCart([null, {id: 999, quantity: 1}, {id: 5, quantity: -1}]), []);
assert.deepEqual(normalizeCart([{id: 1, quantity: 2}, {id: 2, quantity: 1}]), [{id: 1, quantity: 1}]);
cart = cart.filter(row => row.id !== 1);
assert.equal(addProduct(cart, products[1]).warning, '');
assert.deepEqual(normalizeCart({bad: true}), []);
console.log('Passed cart rules, totals, quantity validation, removal, and saved-data round trip.');
